version: '3.8'

services:
    db:
        container_name: currency-db
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: menu
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./storage/db:/var/lib/mysql
        ports:
            - '3307:3306'
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 5s
            retries: 20
    app:
        container_name: currency-app
        build:
            context: .
        ports:
            - '8000:8000'
        depends_on:
            db:
                condition: service_healthy
